public class hardCode {
	public static String  hardCodejason() {
		String var =   '{'+
			'        "evaluation_token": "S-NLa3D9r5cFWfmzOjLHb5",'+
			'        "error": null,'+
			'        "timestamp": 1504854160922,'+
			'        "entity_token": "P-ckoFPa7guqYEYBJFDNQ8",'+
			'        "application_token": "IyKhARmSB6Uys9fhnBDAmNHI1iTWH6tc",'+
			'        "application_version_id": 32,'+
			'        "required": [{'+
			'          "key": "answers",'+
			'          "type": "object",'+
			'          "description": "Object containing answers to out of wallet question prompts.",'+
			'          "template": {'+
			'            "answers": [{'+
			'              "question_id": 1,'+
			'              "answer_id": 0'+
			'            }, {'+
			'              "question_id": 2,'+
			'              "answer_id": 0'+
			'            }, {'+
			'              "question_id": 3,'+
			'              "answer_id": 0'+
			'            }, {'+
			'              "question_id": 4,'+
			'              "answer_id": 0'+
			'            }'+
		   
			'            ]'+
			'          }'+
			'        }],'+
			'        "optional": [],'+
			'        "prompts": {'+
			'          "answers": {'+
			'            "questions": [{'+
			'              "id": 1,'+
			'              "question": "What state was your SSN issued in?",'+
			'              "answers": [{'+
			'                "id": 1,'+
			'                "answer": "Arkansas"'+
			'              }, {'+
			'                "id": 2,'+
			'                "answer": "Alabama"'+
			'              }, {'+
			'                "id": 3,'+
			'                "answer": "West Virginia"'+
			'              }, {'+
			'                "id": 4,'+
			'                "answer": "Virginia"'+
			'              }, {'+
			'                "id": 5,'+
			'                "answer": "None Of The Above"'+
			'              }]'+
			'            }, {'+
			'              "id": 2,'+
			'              "question": "Which one of the following addresses is associated with you?",'+
			'              "answers": [{'+
			'                "id": 1,'+
			'                "answer": "72292 Chestnut Spring Pl"'+
			'              }, {'+
			'                "id": 2,'+
			'                "answer": "16536 Twelve Oaks"'+
			'              }, {'+
			'                "id": 3,'+
			'                "answer": "17845 Sandbox Ln"'+
			'              }, {'+
			'                "id": 4,'+
			'                "answer": "44420 Amstel View Pl"'+
			'              }, {'+
			'                "id": 5,'+
			'                "answer": "None Of The Above"'+
			'              }]'+
			'            } ]'+
			'          }'+
			'        }'+
			'      }';

		return var;
	}
}